// export const HOST = "https://med.ocrv-game.ru/"
export const ROUTER_BASENAME = ""
export const GAME_DOMAIN = "*"
export const BACKEND_DOMAIN = "https://platform.ocrv-game.ru"
export const HOST = "http://localhost:3000/"
